In [1]:
import graph_class as g
import numpy as np

In [2]:
a = np.random.rand(5,5);a

array([[0.14471128, 0.23324649, 0.32257301, 0.2191302 , 0.48292341],
       [0.8832878 , 0.20993521, 0.53511595, 0.10538311, 0.11722284],
       [0.97319619, 0.53653501, 0.34119439, 0.94582069, 0.03825419],
       [0.76950959, 0.04472141, 0.17253595, 0.46790127, 0.11136645],
       [0.28363622, 0.5801075 , 0.88025846, 0.86318465, 0.6646363 ]])

In [3]:
b = g.graph_from_adjacency_matrix(a);b.weighted_adjacency_matrix

array([[       inf, 0.23324649, 0.32257301, 0.2191302 , 0.48292341],
       [0.23324649,        inf, 0.53511595, 0.10538311, 0.11722284],
       [0.32257301, 0.53511595,        inf, 0.94582069, 0.03825419],
       [0.2191302 , 0.10538311, 0.94582069,        inf, 0.11136645],
       [0.48292341, 0.11722284, 0.03825419, 0.11136645,        inf]])

In [4]:
c = np.random.rand(5,2);c

array([[0.81246696, 0.85659766],
       [0.58860195, 0.92125758],
       [0.03345214, 0.88291256],
       [0.89418764, 0.45627957],
       [0.70307844, 0.69432786]])

In [5]:
#default distance is nearest int euclidean 2D
d =g.fully_connected_graph_from_coordinate_list(c);d.weighted_adjacency_matrix

array([[inf,  0.,  1.,  0.,  0.],
       [ 0., inf,  1.,  1.,  0.],
       [ 1.,  1., inf,  1.,  1.],
       [ 0.,  1.,  1., inf,  0.],
       [ 0.,  0.,  1.,  0., inf]])